2020-11-08 12:48:25,610:blog:WARNING:Invalid input params: {'json': {'description': ['Missing data for required field.'], 'name': ['Missing data for required field.']}}
2020-11-08 12:48:30,212:blog:WARNING:Invalid input params: {'json': {'description': ['Missing data for required field.'], 'name': ['Missing data for required field.']}}
2020-12-16 21:09:43,534:event:WARNING:managers - read action failed with errors: name 'desc' is not defined
2020-12-17 20:10:57,249:event:WARNING:arenas - whrite action failed with errors: (pymysql.err.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`mydb`.`arena`, CONSTRAINT `arena_ibfk_1` FOREIGN KEY (`city_id`) REFERENCES `city` (`id`))')
[SQL: INSERT INTO arena (name, description, typehall_id, adres, phone_admin, number_of_seats, hall_size, razgruzka, sound, phone_sound, light, phone_light, city_id, edit_arena, created_arena) VALUES (%(name)s, %(description)s, %(typehall_id)s, %(adres)s, %(phone_admin)s, %(number_of_seats)s, %(hall_size)s, %(razgruzka)s, %(sound)s, %(phone_sound)s, %(light)s, %(phone_light)s, %(city_id)s, %(edit_arena)s, %(created_arena)s)]
[parameters: {'name': 'vfdve', 'description': 'erefew', 'typehall_id': None, 'adres': None, 'phone_admin': None, 'number_of_seats': None, 'hall_size': None, 'razgruzka': None, 'sound': None, 'phone_sound': None, 'light': None, 'phone_light': None, 'city_id': '0', 'edit_arena': datetime.datetime(2020, 12, 17, 17, 10, 57, 243237), 'created_arena': datetime.datetime(2020, 12, 17, 17, 10, 57, 243251)}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2020-12-17 22:20:08,229:event:WARNING:arenas -  action failed with errors: invalid literal for int() with base 10: 'sadsa'
2020-12-17 22:20:18,269:event:WARNING:arenas -  action failed with errors: invalid literal for int() with base 10: 'sad'
2020-12-17 22:20:54,212:event:WARNING:arenas -  action failed with errors: invalid literal for int() with base 10: 'sad'
2020-12-17 22:20:58,781:event:WARNING:arenas -  action failed with errors: invalid literal for int() with base 10: 'asda'
2020-12-17 22:21:02,775:event:WARNING:arenas -  action failed with errors: invalid literal for int() with base 10: 'ewfewfewwfef'
2020-12-17 23:37:56,206:event:WARNING:arenas -  action failed with errors: invalid literal for int() with base 10: 'asdaa'
2020-12-17 23:38:01,527:event:WARNING:arenas -  action failed with errors: invalid literal for int() with base 10: 'kwljqrrkjqr'
2020-12-18 21:58:07,500:event:WARNING:arenas - whrite action failed with errors: (pymysql.err.DataError) (1366, "Incorrect integer value: '' for column 'number_of_seats' at row 1")
[SQL: INSERT INTO arena (name, description, city_id, typehall_id, address, phone_admin, number_of_seats, hall_size, razgruzka, sound, phone_sound, light, phone_light, edit_arena, created_arena) VALUES (%(name)s, %(description)s, %(city_id)s, %(typehall_id)s, %(address)s, %(phone_admin)s, %(number_of_seats)s, %(hall_size)s, %(razgruzka)s, %(sound)s, %(phone_sound)s, %(light)s, %(phone_light)s, %(edit_arena)s, %(created_arena)s)]
[parameters: {'name': 'Триумф', 'description': '', 'city_id': '25', 'typehall_id': '2', 'address': '', 'phone_admin': '', 'number_of_seats': '', 'hall_size': '', 'razgruzka': '', 'sound': '', 'phone_sound': '', 'light': '', 'phone_light': '', 'edit_arena': datetime.datetime(2020, 12, 18, 18, 58, 7, 496845), 'created_arena': datetime.datetime(2020, 12, 18, 18, 58, 7, 496864)}]
(Background on this error at: http://sqlalche.me/e/13/9h9h)
2020-12-18 22:02:46,978:event:WARNING:arenas - whrite action failed with errors: (pymysql.err.DataError) (1366, "Incorrect integer value: '' for column 'number_of_seats' at row 1")
[SQL: INSERT INTO arena (name, description, city_id, typehall_id, address, phone_admin, number_of_seats, hall_size, razgruzka, sound, phone_sound, light, phone_light, edit_arena, created_arena) VALUES (%(name)s, %(description)s, %(city_id)s, %(typehall_id)s, %(address)s, %(phone_admin)s, %(number_of_seats)s, %(hall_size)s, %(razgruzka)s, %(sound)s, %(phone_sound)s, %(light)s, %(phone_light)s, %(edit_arena)s, %(created_arena)s)]
[parameters: {'name': 'Триумф', 'description': '', 'city_id': '25', 'typehall_id': '2', 'address': '', 'phone_admin': '', 'number_of_seats': '', 'hall_size': '', 'razgruzka': '', 'sound': '', 'phone_sound': '', 'light': '', 'phone_light': '', 'edit_arena': datetime.datetime(2020, 12, 18, 19, 2, 46, 976476), 'created_arena': datetime.datetime(2020, 12, 18, 19, 2, 46, 976492)}]
(Background on this error at: http://sqlalche.me/e/13/9h9h)
2020-12-18 22:10:24,499:event:WARNING:arenas - wright action failed with errors: (pymysql.err.DataError) (1366, "Incorrect integer value: '' for column 'number_of_seats' at row 1")
[SQL: INSERT INTO arena (name, description, city_id, typehall_id, address, phone_admin, number_of_seats, hall_size, razgruzka, sound, phone_sound, light, phone_light, edit_arena, created_arena) VALUES (%(name)s, %(description)s, %(city_id)s, %(typehall_id)s, %(address)s, %(phone_admin)s, %(number_of_seats)s, %(hall_size)s, %(razgruzka)s, %(sound)s, %(phone_sound)s, %(light)s, %(phone_light)s, %(edit_arena)s, %(created_arena)s)]
[parameters: {'name': 'Триумф', 'description': '', 'city_id': '25', 'typehall_id': '7', 'address': '', 'phone_admin': '', 'number_of_seats': '', 'hall_size': '', 'razgruzka': '', 'sound': '', 'phone_sound': '', 'light': '', 'phone_light': '', 'edit_arena': datetime.datetime(2020, 12, 18, 19, 10, 24, 496486), 'created_arena': datetime.datetime(2020, 12, 18, 19, 10, 24, 496500)}]
(Background on this error at: http://sqlalche.me/e/13/9h9h)
2020-12-18 22:12:37,846:event:WARNING:arenas - wright action failed with errors: (pymysql.err.DataError) (1366, "Incorrect integer value: '' for column 'number_of_seats' at row 1")
[SQL: INSERT INTO arena (name, description, city_id, typehall_id, address, phone_admin, number_of_seats, hall_size, razgruzka, sound, phone_sound, light, phone_light, edit_arena, created_arena) VALUES (%(name)s, %(description)s, %(city_id)s, %(typehall_id)s, %(address)s, %(phone_admin)s, %(number_of_seats)s, %(hall_size)s, %(razgruzka)s, %(sound)s, %(phone_sound)s, %(light)s, %(phone_light)s, %(edit_arena)s, %(created_arena)s)]
[parameters: {'name': 'Триумф', 'description': '', 'city_id': '25', 'typehall_id': '2', 'address': '', 'phone_admin': '', 'number_of_seats': '', 'hall_size': '', 'razgruzka': '', 'sound': '', 'phone_sound': '', 'light': '', 'phone_light': '', 'edit_arena': datetime.datetime(2020, 12, 18, 19, 12, 37, 842503), 'created_arena': datetime.datetime(2020, 12, 18, 19, 12, 37, 842527)}]
(Background on this error at: http://sqlalche.me/e/13/9h9h)
2020-12-18 22:14:46,984:event:WARNING:arenas - wright action failed with errors: (pymysql.err.DataError) (1366, "Incorrect integer value: '' for column 'number_of_seats' at row 1")
[SQL: INSERT INTO arena (name, description, city_id, typehall_id, address, phone_admin, number_of_seats, hall_size, razgruzka, sound, phone_sound, light, phone_light, edit_arena, created_arena) VALUES (%(name)s, %(description)s, %(city_id)s, %(typehall_id)s, %(address)s, %(phone_admin)s, %(number_of_seats)s, %(hall_size)s, %(razgruzka)s, %(sound)s, %(phone_sound)s, %(light)s, %(phone_light)s, %(edit_arena)s, %(created_arena)s)]
[parameters: {'name': 'Триумф', 'description': '', 'city_id': '25', 'typehall_id': '2', 'address': '', 'phone_admin': '', 'number_of_seats': '', 'hall_size': '', 'razgruzka': '', 'sound': '', 'phone_sound': '', 'light': '', 'phone_light': '', 'edit_arena': datetime.datetime(2020, 12, 18, 19, 14, 46, 980525), 'created_arena': datetime.datetime(2020, 12, 18, 19, 14, 46, 980542)}]
(Background on this error at: http://sqlalche.me/e/13/9h9h)
2020-12-18 23:08:34,713:event:WARNING:user: Vestimy tutorials - read action failed with errors: Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with Tour.event has an attribute 'date_event'
2020-12-18 23:08:51,724:event:WARNING:user: Vestimy tutorials - read action failed with errors: Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with Tour.event has an attribute 'date_event'
2020-12-18 23:10:19,117:event:WARNING:user: Vestimy tours - read action failed with errors: Can't resolve label reference for ORDER BY / GROUP BY / DISTINCT etc. Textual SQL expression 'Tour.event.date_event[0]' should be explicitly declared as text('Tour.event.date_event[0]')
2020-12-18 23:12:04,524:event:WARNING:user: Vestimy tours - read action failed with errors: (pymysql.err.OperationalError) (1054, "Unknown column 'event.tour_id' in 'order clause'")
[SQL: SELECT tour.id AS tour_id, tour.name AS tour_name, tour.edit_tour AS tour_edit_tour, tour.created_tour AS tour_created_tour 
FROM tour ORDER BY tour.id = event.tour_id]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
2020-12-18 23:12:32,846:event:WARNING:user: Vestimy tours - read action failed with errors: Can't resolve label reference for ORDER BY / GROUP BY / DISTINCT etc. Textual SQL expression 'event.date_event' should be explicitly declared as text('event.date_event')
2020-12-18 23:12:43,839:event:WARNING:user: Vestimy tours - read action failed with errors: Can't resolve label reference for ORDER BY / GROUP BY / DISTINCT etc. Textual SQL expression 'date_event' should be explicitly declared as text('date_event')
2020-12-19 23:14:20,922:event:WARNING:managers - reads action failed with errors: Can't resolve label reference for ORDER BY / GROUP BY / DISTINCT etc. Textual SQL expression 'name' should be explicitly declared as text('name')
2020-12-19 23:15:03,369:event:WARNING:managers - reads action failed with errors: Can't resolve label reference for ORDER BY / GROUP BY / DISTINCT etc. Textual SQL expression 'name' should be explicitly declared as text('name')
2020-12-19 23:19:23,743:event:WARNING:managers - reads action failed with errors: Can't resolve label reference for ORDER BY / GROUP BY / DISTINCT etc. Textual SQL expression 'name' should be explicitly declared as text('name')
2020-12-20 00:36:43,849:event:WARNING:managers - reads action failed with errors: Can't resolve label reference for ORDER BY / GROUP BY / DISTINCT etc. Textual SQL expression 'name' should be explicitly declared as text('name')
2020-12-20 01:14:42,242:event:WARNING:managers - reads action failed with errors: Can't resolve label reference for ORDER BY / GROUP BY / DISTINCT etc. Textual SQL expression 'name' should be explicitly declared as text('name')
2020-12-20 01:16:50,113:event:WARNING:managers - reads action failed with errors: Can't resolve label reference for ORDER BY / GROUP BY / DISTINCT etc. Textual SQL expression 'name' should be explicitly declared as text('name')
2020-12-20 01:17:23,706:event:WARNING:managers - reads action failed with errors: Can't resolve label reference for ORDER BY / GROUP BY / DISTINCT etc. Textual SQL expression 'name' should be explicitly declared as text('name')
2020-12-20 01:17:58,636:event:WARNING:managers - reads action failed with errors: 'function' object has no attribute 'any'
2020-12-20 01:17:59,683:event:WARNING:managers - reads action failed with errors: 'function' object has no attribute 'any'
2020-12-20 01:18:11,403:event:WARNING:managers - reads action failed with errors: 'function' object has no attribute 'any'
2020-12-20 01:19:27,125:event:WARNING:managers - reads action failed with errors: type object 'User' has no attribute 'role'
2020-12-20 01:19:28,469:event:WARNING:managers - reads action failed with errors: type object 'User' has no attribute 'role'
2020-12-20 01:19:28,807:event:WARNING:managers - reads action failed with errors: type object 'User' has no attribute 'role'
2020-12-20 01:19:29,278:event:WARNING:managers - reads action failed with errors: type object 'User' has no attribute 'role'
2020-12-20 01:21:58,365:event:WARNING:managers - reads action failed with errors: 'method' object is not subscriptable
2020-12-20 01:21:59,080:event:WARNING:managers - reads action failed with errors: 'method' object is not subscriptable
2020-12-20 01:23:35,056:event:WARNING:managers - read action failed with errors: type object 'Event' has no attribute 'manager_id'
2020-12-20 01:23:54,099:event:WARNING:managers - read action failed with errors: type object 'Event' has no attribute 'manager_id'
2020-12-20 01:28:04,659:event:WARNING:managers - read action failed with errors: type object 'Event' has no attribute 'manager_id'
2020-12-20 01:28:09,560:event:WARNING:managers - read action failed with errors: type object 'Event' has no attribute 'manager_id'
2020-12-20 01:29:02,888:event:WARNING:managers - read action failed with errors: type object 'Event' has no attribute 'manager_id'
2020-12-20 20:47:21,768:event:WARNING:managers - read action failed with errors: name 'desc' is not defined
2020-12-20 20:47:34,905:event:WARNING:managers - read action failed with errors: 'BaseQuery' object has no attribute 'desc'
2020-12-20 20:49:44,438:event:WARNING:managers - read action failed with errors: 'BaseQuery' object has no attribute 'desc'
2020-12-20 20:49:45,384:event:WARNING:managers - read action failed with errors: 'BaseQuery' object has no attribute 'desc'
2020-12-20 20:49:56,308:event:WARNING:managers - read action failed with errors: 'BaseQuery' object has no attribute 'desc'
2020-12-20 20:49:57,112:event:WARNING:managers - read action failed with errors: 'BaseQuery' object has no attribute 'desc'
2020-12-21 18:20:28,718:event:WARNING:Вестимый Андрей - Ошибка при обновлении профиля
2020-12-21 18:21:11,461:event:WARNING:Вестимый Андрей - Ошибка при обновлении профиля: name 'upl' is not defined
2020-12-21 19:24:35,411:event:WARNING:Вестимый Андрей - Ошибка при удалении менеджера: 'BaseQuery' object has no attribute '_sa_instance_state'
2020-12-21 19:25:21,484:event:WARNING:Вестимый Андрей - Ошибка при удалении менеджера: 'BaseQuery' object has no attribute '_sa_instance_state'
2020-12-22 17:45:37,646:event:WARNING:arenas - wright action failed with errors: (pymysql.err.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`mydb`.`arena`, CONSTRAINT `arena_ibfk_1` FOREIGN KEY (`city_id`) REFERENCES `city` (`id`))')
[SQL: INSERT INTO arena (name, description, city_id, typehall_id, address, phone_admin, number_of_seats, hall_size, razgruzka, sound, phone_sound, light, phone_light, edit_arena, created_arena) VALUES (%(name)s, %(description)s, %(city_id)s, %(typehall_id)s, %(address)s, %(phone_admin)s, %(number_of_seats)s, %(hall_size)s, %(razgruzka)s, %(sound)s, %(phone_sound)s, %(light)s, %(phone_light)s, %(edit_arena)s, %(created_arena)s)]
[parameters: {'name': 'Ласточка', 'description': '', 'city_id': '0', 'typehall_id': '2', 'address': '', 'phone_admin': '', 'number_of_seats': '', 'hall_size': '', 'razgruzka': '', 'sound': '', 'phone_sound': '', 'light': '', 'phone_light': '', 'edit_arena': datetime.datetime(2020, 12, 22, 14, 45, 37, 638175), 'created_arena': datetime.datetime(2020, 12, 22, 14, 45, 37, 638204)}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
